latex_names = {
  '4l': '$4\ell$',
  '2e2mu': '$2e2\mu$',
  'mass4l': '$m_{4l}$',
  'mass4l_zzfloating': '$m_{4l}$',
  'Nj': '$N_{jet}$',
  'Nj_zzfloating': '$N_{jet}$',
  'pT4l': '$p_{T}^{H}$',
  'pT4l_zzfloating': '$p_{T}^{H}$',
  'rapidity4l': '$|y_{H}|$',
  'rapidity4l_zzfloating': '$|y_{H}|$',
  'costhetaZ1': '$cos(\\theta_{1})$',
  'costhetaZ1_zzfloating': '$cos(\\theta_{1})$',
  'costhetaZ2': '$cos(\\theta_{2})$',
  'costhetaZ2_zzfloating': '$cos(\\theta_{2})$',
  'phi': '$\\Phi$',
  'phi_zzfloating': '$\\Phi$',
  'phi1': '$\\Phi^{\\star}$',
  'phi1_zzfloating': '$\\Phi^{\\star}$',
  'costhetastar': '$cos(\\theta^{*})$',
  'costhetastar_zzfloating': '$cos(\\theta^{*})$',
  'massZ1': '$m_{Z1}$',
  'massZ1_zzfloating': '$m_{Z1}$',
  'massZ2': '$m_{Z2}$',
  'massZ2_zzfloating': '$m_{Z2}$',
  'pTj1': '$p_{T}^{(j1, 4.7)}$',
  'pTj1_zzfloating': '$p_{T}^{(j1, 4.7)}$',
  'pTHj': '$p_{T}^{Hj}$',
  'pTHj_zzfloating': '$p_{T}^{Hj}$',
  'mHj': '$m_{Hj}$',
  'mHj_zzfloating': '$m_{Hj}$',
  'pTj2': '$p_{T}^{(j2, 4.7)}$',
  'pTj2_zzfloating': '$p_{T}^{(j2, 4.7)}$',
  'mjj': '$m_{jj}$',
  'mjj_zzfloating': '$m_{jj}$',
  'absdetajj': '$|\\Delta\\Eta_{jj}|$',
  'absdetajj_zzfloating': '$|\\Delta\\Eta_{jj}|$',
  'dphijj': '$|\\Delta\\Phi_{jj}|$',
  'dphijj_zzfloating': '$|\\Delta\\Phi_{jj}|$',
  'pTHjj': '$p_{T}^{Hjj}$',
  'pTHjj_zzfloating': '$p_{T}^{Hjj}$',
  'TCjmax': '$\\mathrm{T}_{\\mathrm{C},{j}}$',
  'TCjmax_zzfloating': '$\\mathrm{T}_{\\mathrm{C},{j}}$',
  'TBjmax': '$\\mathrm{T}_{\\mathrm{B},{j}}$',
  'TBjmax_zzfloating': '$\\mathrm{T}_{\\mathrm{B},{j}}$',
  'D0m': '$D_{0m}$',
  'D0m_zzfloating': '$D_{0m}$',
  'Dcp': '$D_{cp}$',
  'Dcp_zzfloating': '$D_{cp}$',
  'D0hp': '$D_{0h^{+}}$',
  'D0hp_zzfloating': '$D_{0h^{+}}$',
  'Dint': '$D_{int}$',
  'Dint_zzfloating': '$D_{int}$',
  'DL1': '$D_{\\Lambda1}$',
  'DL1_zzfloating': '$D_{\\Lambda1}$',
  'DL1Zg': '$D_{\\Lambda1,Z\\gamma}$',
  'DL1Zg_zzfloating': '$D_{\\Lambda1,Z\\gamma}$',
    'rapidity4l_pT4l': '$|y_{H}|$ vs $p_{T}^{H}$',
    'rapidity4l_pT4l_zzfloating': '$|y_{H}|$ vs $p_{T}^{H}$',
    'massZ1_massZ2': '$m_{Z1}$ vs $m_{Z2}$',
    'massZ1_massZ2_zzfloating': '$m_{Z1}$ vs $m_{Z2}$',
    'pTj1_pTj2': '$p_{T}^{(j1, 4.7)}$ vs $p_{T}^{(j2, 4.7)}$',
    'pTj1_pTj2_zzfloating': '$p_{T}^{(j1, 4.7)}$ vs $p_{T}^{(j2, 4.7)}$',
    'Nj_pT4l': '$N_{jet}$ vs $p_{T}^{H}$',
    'Nj_pT4l_zzfloating': '$N_{jet}$ vs $p_{T}^{H}$',
    'pT4l_pTHj': '$p_{T}^{H}$ vs $p_{T}^{Hj}$',
    'pT4l_pTHj_zzfloating': '$p_{T}^{H}$ vs $p_{T}^{Hj}$',
    'absdetajj_mjj': '$|\\Delta\\Eta_{jj}|$ vs $m_{jj}$',
    'absdetajj_mjj_zzfloating': '$|\\Delta\\Eta_{jj}|$ vs $m_{jj}$',
    'TCjmax_pT4l': '$\\mathrm{T}_{\\mathrm{C},{j}}$ vs $p_{T}^{H}$',
    'TCjmax_pT4l_zzfloating': '$\\mathrm{T}_{\\mathrm{C},{j}}$ vs $p_{T}^{H}$',
}
