universe   = vanilla
executable = run_step3.sh
arguments  = $(obsName) $(year)
output     = logs/$(ClusterId).$(Process).out
error      = logs/$(ClusterId).$(Process).err
log        = logs/$(ClusterId).$(Process).log

+JobFlavour = "nextweek"

request_memory = 24000

transfer_input_files = /afs/cern.ch/user/s/sellissp/public/HZZ/CMSSW_14_1_0_pre4/src/FiducialXSFWK/coefficients/RunCoefficients.py, /afs/cern.ch/user/s/sellissp/public/HZZ/CMSSW_14_1_0_pre4/src/FiducialXSFWK/templates/RunTemplates.py, /afs/cern.ch/user/s/sellissp/public/HZZ/CMSSW_14_1_0_pre4/src/FiducialXSFWK/fit/RunFiducialXS.py, /afs/cern.ch/user/s/sellissp/public/HZZ/CMSSW_14_1_0_pre4/src/FiducialXSFWK/fit/expected_xsec_allPmodes.py, /afs/cern.ch/user/s/sellissp/public/HZZ/CMSSW_14_1_0_pre4/src/FiducialXSFWK/LHScans/plot_LLScan.py, /afs/cern.ch/user/s/sellissp/public/HZZ/CMSSW_14_1_0_pre4/src/FiducialXSFWK/coefficients/PILEUP/RunPileup.py

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

queue obsName, year from input_args.txt